name: An Introduction to Principle Component Analysis
category: analysis
authors: ""
shortdesc: The aim of this course is to illustrate methods we can use to assess convergence and sampling in MD trajectories.
longdesc: ""
